// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzhknrvzntcymvzeepkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6aGtucnZ6bnRjeW12emVlcGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDA0MzIsImV4cCI6MjA2NDE3NjQzMn0.STJkfLI4yGp8qnddNcPXRu3t2jxg5p6QyIB4QVr-IgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);